---
title: "Annot object: Working with results"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Annot object: Working with results}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Introduction
Annot is the resulting object of the MS2ID::annotate() function. In a typical workflow user browses the containing results via the MS2ID browser (MS2IDgui() function) or exporting them to an xlsx file (export2xlsx()). Moreover, all spectra and metadata can be accesed with get functions and handled using  the Spectra package (Rainer et al)

## MS2ID browser
MS2IDgui() opens a Shiny app that browses all the data contained into the Annot object. Also graphically compares both related spectra (query spectrum versus reference spectrum) and shows the formation of the query spectrum when is made up as consensus of differents query spectra. 
See more info 
Image
Rainer



with the reference spectra its refernece counterpart    Annot is the resulting object of the MS2ID::annotate() function. In a typical workflow user browses the containing results via the MS2ID browser (MS2IDgui() function) or exporting them to an xlsx file (export2xlsx()). Moreover, all spectra and metadata can be accesed with get functions and handled using  the Spectra package (Rainer et al)
This object stores the annotation results so we can extract particular content by using them *getters* (custom functions to *get* the info) or save the whole object for further analysis (use saveRDS() and loadRDS()).

## Using Getters:    
* **hits()**: returns a cross-reference dataframe containing the hits along with their proposed adducts and common masses.
* **qrySpectra()**: returns an Spectra object (see [Spectra](https://www.bioconductor.org/packages/release/bioc/html/Spectra.html) package) containing the query spectra with hits.
* **refSpectra()**: returns an Spectra object with the successful reference spectra.
* **refCompound()**: returns a dataframe containing (reference) compound metadata of successful reference spectra.
* **infoAnnotation()**: returns the variables used on the annotation process.

## Build an in-house MS2 spectra libraryexit  object stores the annotation results so we can extract particular content by appplying them *getters* (custom functions to *get* the info) or save the whole object for further analysis (use saveRDS() and loadRDS()).

### Getters:    
* **hits()**: returns a cross-reference dataframe containing the hits along with their proposed adducts and common masses.
* **qrySpectra()**: returns an Spectra object (see [Spectra](https://www.bioconductor.org/packages/release/bioc/html/Spectra.html) package) containing the query spectra with hits.
* **refSpectra()**: returns an Spectra object with the successful reference spectra.
* **refCompound()**: returns a dataframe containing (reference) compound metadata of successful reference spectra.
* **infoAnnotation()**: returns the variables used on the annotation process.

## Build an in-house MS2 spectra library
